server:
  port: 8082

spring:
  application:
    name: REVIEWS-SERVICE
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:reviews
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect