server:
  port: 8081

spring:
  application:
    name: COMPANY-SERVICE
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:9296}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/companydb
    username: ${USERNAME:postgres}
    password: ${PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    customer:
      bootstrap-servers: ${KAFKA_SERVER:http://localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: reviewers
      auto-offset-rest: earliest