apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://configserver-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service: "http://eureka-0.eureka:8761/eureka"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
data:
  hostname: "postgres-0.postgres"
  username: "postgres"
  password: "root"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-cm
data:
  username: "ConfidenceDev"
  token: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  zookeeper_id: "1"
  zookeeper_server: "server.1=zookeeper:2888:3888"
  kafka_broker_id: "1"
  kafka_zookeeper_connect: "zookeeper:2181"
  kafka_advertised_listeners: "PLAINTEXT://kafka:9092"
  kafka_listeners: "PLAINTEXT://0.0.0.0:9092"
