apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://configserver-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service: "http://eureka-0.eureka:8761/eureka"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
data:
  hostname: "postgres-0.postgres"
  username: "postgres"
  password: "root"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-cm
data:
  username: "ConfidenceDev"
  token: ""
